In [4]:
# Liner regression with normal equation
import numpy as np
from sklearn.datasets import fetch_california_housing
import tensorflow as tf

In [5]:
housing = fetch_california_housing()


In [6]:
housing.data.shape

(20640, 8)

In [7]:
m, n = housing.data.shape

In [8]:
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]


In [9]:
housing_data_plus_bias

array([[   1.        ,    8.3252    ,   41.        , ...,    2.55555556,
          37.88      , -122.23      ],
       [   1.        ,    8.3014    ,   21.        , ...,    2.10984183,
          37.86      , -122.22      ],
       [   1.        ,    7.2574    ,   52.        , ...,    2.80225989,
          37.85      , -122.24      ],
       ..., 
       [   1.        ,    1.7       ,   17.        , ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.        ,    1.8672    ,   18.        , ...,    2.12320917,
          39.43      , -121.32      ],
       [   1.        ,    2.3886    ,   16.        , ...,    2.61698113,
          39.37      , -121.24      ]])

In [10]:
X = tf.constant(housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
XT = tf.transpose(X)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), y)

In [11]:
with tf.Session() as sess:
    theta_value = theta.eval()

In [12]:
theta_value


array([[ -3.71851807e+01],
       [  4.36337471e-01],
       [  9.39523336e-03],
       [ -1.07113101e-01],
       [  6.44792199e-01],
       [ -4.03380000e-06],
       [ -3.78137082e-03],
       [ -4.23484027e-01],
       [ -4.37219113e-01]], dtype=float32)

In [13]:
# the same as above but with pure numpy
X = housing_data_plus_bias
y = housing.target.reshape(-1, 1)
theta_numpy = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

print(theta_numpy)


[[ -3.69419202e+01]
 [  4.36693293e-01]
 [  9.43577803e-03]
 [ -1.07322041e-01]
 [  6.45065694e-01]
 [ -3.97638942e-06]
 [ -3.78654265e-03]
 [ -4.21314378e-01]
 [ -4.34513755e-01]]
